### PR TITLE
use Int64 for all integers that end up bitcast to UInt64

### LINKED ISSUE #22: 32 bit not working
First off, great package! I just tried switching GeoJSON.jl over to this use package ([PR](https://github.com/JuliaGeo/GeoJSON.jl/pull/22)). But I noticed AppVeyor 32 bit failed with [`bitcast: argument size does not match size of target type`](https://ci.appveyor.com/project/JuliaGeo/geojson-jl/builds/26620540/job/lnya349bd5qfb23q#L62).

I see there is an appveyor.yml, but the service doesn't seem like it is turned on. It would help to catch 32 bit errors. In this case this line fails:
https://github.com/quinnj/JSON3.jl/blob/37ab02e420692965ff33cfd8a343a5b43c97c338/src/utils.jl#L71
Since `len` is an `Int` i.e. `Int32` on 32 bit, which refuses to cast to 64 bits.
The `Int` comes from here:
https://github.com/quinnj/JSON3.jl/blob/37ab02e420692965ff33cfd8a343a5b43c97c338/src/read.jl#L195

### PR DESCRIPTION
**Pull request by visr**
Fixes #22

This patch should not have any effect on 64 bit systems.

Alternatively we can define these additional methods, not sure what is better.
```julia
object(tapelen::Int32) = OBJECT | convert(UInt64, tapelen)
array(tapelen::Int32)  = ARRAY  | convert(UInt64, tapelen)
eltypelen(T, len::Int32) = T | convert(UInt64, len)
string(len::Int32) = STRING | convert(UInt64, len)
```

### CODE REVIEW

File: src/show.jl [hunk 1]
```diff
@@ -1,4 +1,5 @@
 Base.show(io::IO, j::Object) = _show(io, j)
+Base.show(io::IO, j::Array) = _show(io, j)
```
Comment (quinnj) [inline src/show.jl]: This was taken out recently because people wanted the normal fallback `AbstractArray` show method

Comment (visr) [reply src/show.jl]: Ah sorry let me take that out again, I assumed it was an oversight.

**Comment by visr** [comment]
Great, thanks! You may still want to enable AppVeyor, or [add 32 bit Windows to Travis](https://discourse.julialang.org/t/julia-is-now-available-on-travis-windows-builds/27187), to make sure it stays working.

**Comment by quinnj** [comment]
Ah yes, done! https://ci.appveyor.com/project/quinnj/json3-jl
